### ISSUE TITLE
Wiki page update

### ISSUE THREAD

**Issue by shuklaalok7** [gmessner/gitlab4j-api#208] opened 2018-07-02 02:31 UTC
HTTP status 500 encountered consistently when using `WikisApi.updatePage(...)` method. I am still investigating it. This issue is related to #189 and #191.

![image](https://user-images.githubusercontent.com/1621571/42142622-035cf97a-7dce-11e8-8e21-70f8e2ecd38a.png)

**Comment by shuklaalok7** [comment] 2018-07-06 16:30
Strange, the test is getting passed without any problem but when I call it in my other project, where I am using this library, it gives `500 Internal Server Error`. Still looking into cause of it. It may happen that the problem is not in this library but with my other project.

**Comment by gmessner** [comment] 2018-07-08 00:29
@shuklaalok7 
The Wiki API was not added until GitLab 10.0, is it possible that the other server is older than 10.0 ?

**Comment by gmessner** [comment] 2018-07-13 17:43
@shuklaalok7 
I've tested this against my GitLab CE server and can find no problems, have you come up with anything?

**Comment by gmessner** [comment] 2018-07-25 05:47
@shuklaalok7 
Can this issue be closed?

**Comment by gmessner** [comment] 2018-07-29 23:31
@shuklaalok7 
I'm going to close this issue, you can always re-open if you discover that the problem is with this library.

**Closed by gmessner** 2018-07-29 23:31 UTC
