### ISSUE TITLE
Project API "Upload a file" and "Push Rules"

### ISSUE THREAD

**Issue by jflefebvre06** [gmessner/gitlab4j-api#171] opened 2018-04-09 12:48 UTC
Could you please add méthods to projectApi to upload file (https://docs.gitlab.com/ee/api/projects.html#upload-a-file) and manage push rules (https://docs.gitlab.com/ee/api/projects.html#push-rules)

**Comment by gmessner** [comment] 2018-04-11 06:26
These will be added in the next release of GitLab4J, scheduled for the week of 4/16/2018.

**Comment by jflefebvre06** [comment] 2018-04-11 07:45
@gmessner  Thanks a lot

**Comment by gmessner** [comment] 2018-04-15 03:54
@jflefebvre06 
I noticed what I believe is a bug with the GitLab API docs for updating and deleting a push rule. 
 Unfortunately, I do not have access to an EE version of GitLab so I cannot test.  The problem is that there is no push rule ID specified in the docs when updating or deleting, see:

https://docs.gitlab.com/ee/api/projects.html#edit-project-push-rule
https://docs.gitlab.com/ee/api/projects.html#delete-project-push-rule

Notice that no push rule ID is specified.  I'm pretty sure that the push rule ID should be the last item in the URL, can you confirm this?

**Comment by gmessner** [comment] 2018-04-19 23:02
@jflefebvre06 
Just pinging you to see if you had an opportunity to test the Push Rule functionality?

**Comment by gmessner** [comment] 2018-04-24 02:35
@jflefebvre06 
The reworked push rule support is completed and released.  Would greatly appreciate it if you could test the new functionality.  I cannot test because this is a GitLab-EE feature.

**Comment by gmessner** [comment] 2018-04-26 22:47
@jflefebvre06 
I'm going to assume that the push rules functionality is working and close this issue.  If you find that the push rules functionality is not working, please re-open this issue.

**Closed by gmessner** 2018-04-26 22:47 UTC
Labels: enhancement

**Comment by jflefebvre06** [comment] 2018-05-23 08:22
Hello,
I am very sorry for the delay, I was at the hospital ...
It not seems to work, when I try to update pushrules I get `InboundJaxrsResponse{context=ClientResponse{method=POST, uri=https://iXXX/api/v4/projects/6433/push_rule, status=422, reason=Unprocessable Entity}}`

**Comment by gmessner** [comment] 2018-05-23 13:55
@jflefebvre06 
Hope you are doing better.

Unfortunately I am not able to debug this issue because I do not have access to a GitLab Enterprise Edition server.  The PushRules only work on GitLab-EE, it would be very helpful if you were able to debug and fix.

**Comment by jflefebvre06** [comment] 2018-05-23 14:14
Sure, I will try to di IT ASAP

**Comment by jflefebvre06** [comment] 2018-06-12 13:01
Hello,

Sorry for the delay. The fix for `updatePushRules` is :

```java
public PushRules updatePushRules(final Integer projectId, final PushRules pushRule) throws GitLabApiException {
        ....
        final Response response = this.post(Response.Status.OK, formData, "projects", projectId, "push_rule");
        return response.readEntity(PushRules.class);
    }
```

replaced by

```java
public PushRules updatePushRules(final Integer projectId, final PushRules pushRule) throws GitLabApiException {
        ....
        final Response response = this.putWithFormData(Response.Status.OK, formData, "projects", projectId, "push_rule");
        return response.readEntity(PushRules.class);
    }
```

**Comment by gmessner** [comment] 2018-06-12 19:00
@jflefebvre06 
Thanks for the fix.  I verified in the documentation that this should have been a PUT, sorry I missed that in the original implementation.

**Comment by jflefebvre06** [comment] 2018-06-14 07:05
Thanks for the release
